### ISSUE TITLE
Inject system dependency

### ISSUE THREAD

**Issue by nbenn** [jimhester/azuretest#12]
I'm trying to figure out how I could make sure that some dependency is installed before the "Install package dependencies" step.

Say I have an `azure-pipelines.yml` like

```yaml
resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: my-endpoint

jobs:
  - template: azure-tidyverse.yml@r-azure-pipelines
```

Is it currently possible to add a step to for example the linux setup, containing some `sudo apt-get update && sudo apt-get install ...` command?

If not, is such a thing in-scope for `r-azure-pipelines` or is the preferred way that we start copy/pasting stuff from `r-azure-pipelines` into our own `azure-pipelines.yml` files in case the required setup contains extra stuff?

More specifically, I have a `r-lib/keyring` dependency in my package and currently `Linux R-3.2` and `Linux R-3.3` fail due to `libsodium-dev` not being available.
