### ISSUE TITLE
R doesn't see R_LIBS_USER environment variable

### ISSUE THREAD

**Issue by hongooi73** [jimhester/azuretest#4]
Hi Jim,

Just wondering if you ran into the problem where R can't seem to find R_LIBS_USER, even though it's set. My basic yaml file, based on your excellent work is:

```yaml
variables:
- group: GH
- name: R_LIBS_USER
  value: '$(Agent.BuildDirectory)/R/library'

pool:
  vmImage: 'ubuntu-latest'

container: rocker/rstudio:latest

steps:
- script: |
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    mkdir -p ${R_LIBS_USER}
  displayName: 'Setup R library directory'

- bash: |
    Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"  <-- problem here
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'

- bash: |
    Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error', check_dir = 'check')"
  displayName: 'Checking package'
```

The problem is in the `bash` step where I install the remotes and rcmdcheck packages, and then run `install_deps`. For some reason R doesn't see the R_LIBS_USER variable, which should expand to something like `/__w/1/R/library`. Because of this, it tries to install to the site-wide location `/usr/local/lib/R/site-library`, which fails because this directory is not user-writeable.

I [asked this on SO](https://stackoverflow.com/questions/57364783/env-variable-not-found-by-r-in-azure-pipeline), but didn't get any useful response. In the end, I resorted to editing `~.Rprofile` to tell R about the library directory.
